import type {
  Evidence,
  EvidenceFrontmatter,
  EvidenceDeployment,
  BundledEvidence,
} from "../types";

// These will be generated by the build script
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Generated at build time
import { evidence, evidenceSlugs } from "./evidence";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - Generated at build time
import { deployments, deploymentSlugs } from "./deployments";

export { evidence, evidenceSlugs, deployments, deploymentSlugs };

export type EvidenceSlug = (typeof evidenceSlugs)[number];
export type DeploymentSlug = (typeof deploymentSlugs)[number];

/**
 * Get evidence by slug
 */
export function getEvidence(slug: string): BundledEvidence | undefined {
  return evidence[slug] as BundledEvidence | undefined;
}

/**
 * Get all evidence slugs
 */
export function getAllEvidenceSlugs(): readonly string[] {
  return evidenceSlugs;
}

/**
 * Get deployment metadata by slug
 */
export function getDeployment(slug: string): EvidenceDeployment | undefined {
  return deployments[slug] as EvidenceDeployment | undefined;
}

/**
 * Get evidence with deployment metadata merged (for display)
 */
export function getEvidenceWithDeployment(slug: string): Evidence | undefined {
  const ev = evidence[slug] as BundledEvidence | undefined;
  const dep = deployments[slug] as EvidenceDeployment | undefined;

  if (!ev) return undefined;

  return {
    ...ev.frontmatter,
    ...(dep
      ? {
          attestationUID: dep.attestationUID,
          ipfsHash: dep.ipfsHash,
          timestamp: dep.timestamp,
          history: dep.history,
        }
      : {}),
  } as Evidence;
}

/**
 * Get all evidence metadata (frontmatter only, for lists)
 */
export function getAllEvidenceMeta(): EvidenceFrontmatter[] {
  return Object.values(evidence as Record<string, BundledEvidence>)
    .map((e) => e.frontmatter)
    .sort((a, b) => {
      const idA = parseInt(a.evidence_id, 10);
      const idB = parseInt(b.evidence_id, 10);
      return idA - idB;
    });
}

/**
 * Get all evidence with deployment metadata merged
 */
export function getAllEvidence(): Evidence[] {
  return (evidenceSlugs as readonly string[])
    .map((slug) => getEvidenceWithDeployment(slug))
    .filter((e): e is Evidence => e !== undefined)
    .sort((a, b) => {
      const idA = parseInt(a.evidence_id, 10);
      const idB = parseInt(b.evidence_id, 10);
      return idA - idB;
    });
}
